### ISSUE TITLE
JAVA_HOME is not used when actually starting Java

### ISSUE THREAD

**Issue by elyograg** [ucomesdag/idrac6-console#1]
I installed JDK7, and set JAVA_HOME to that path.  This script didn't work until I modified it to use JAVA_HOME when calling Java as well as fiddling with the .security file.

Before I go to the trouble of a PR, at the following URL (which expires in one year) is the diff that I think will fix this.  This tries to set JAVA_HOME if it is not already set.  And it puts the java command in a screen if screen is available, so the shell is not littered with debug output.  I also ran the script through shellcheck and made adjustments so that passes.

https://paste.elyograg.org/view/ffce10cb

**Comment by ucomesdag** [comment]
@elyograg Thanks for the improvements! I made some minor changes, let me know what you think before I merge it.

**Comment by elyograg** [comment]
Where can I see what you've got?

**Comment by elyograg** [comment]
At quick glance it looks good.  What did you change from my patch?

I forgot to fix the typo "Start the iDAC6 virtual console".  Which doesn't affect operation in any way.

**Comment by ucomesdag** [comment]
I manually applied your suggested patch expect the added export statements.
