### ISSUE TITLE
Error on macOS arm64 (Apple Silicon)

### ISSUE THREAD

**Issue by second2falcon** [ucomesdag/idrac6-console#3]
So when I try to run ./console.sh, I get the following error:
`./console.sh: line 110: MACOS_${ARCH^^}_LIBS: bad substitution`

I think this is because I am running Apple Silicon (M1) which is arm64.

My knowledge of programming is limited, but it seems to me that theoretically you should be able to run the two .jar files (avctKVMIOMac64.jar and avctVMMac64.jar) with Rosetta (x86_64 to arm64 translation layer).

**Comment by ucomesdag** [comment]
I will try to have a look on a Apple Silicon Mac and circle back here.

**Comment by second2falcon** [comment]
@ucomesdag I have had the problem with lauching it manually too since I reset my MacBook. Probably because I originally copied everything from an Intel MacBook which had x86 Java on it instead of arm64 Java (which probably is installed now).

**Comment by ucomesdag** [comment]
Found the issue, the error `bad substitution` is because the bash version shipped by default on macOS is to old. For command substitution you need at least version 4.0. You can install a newer version with `brew install bash`.

Also fixed the script to treat arm64 as it was x86_64, so it will download the libraries and it now runs on Apple Silicon.

Can you try this branch: https://github.com/ucomesdag/idrac6-console/tree/feat/arm64

**Comment by second2falcon** [comment]
@ucomesdag It works and you were right. Bash 3.5.something was installed. Updated with `brew install bash` and now it works perfectly. Thank you very much. Wasn't able to use iDrac because arm64 vs x86.

Groeten uit de Bollenstreek

**Comment by ucomesdag** [comment]
> PS: is there something planned that we can use a config/credentials file so we don't have to enter username/password every time (maybe only useful for people with one server tho)?

You can use the -p option with a password file, or without and put a password file in $HOME, $PWD or the scripts directory itself.
And if you have only 1 server you can also create an alias, something like `alias idrac-console='~/Developer/idrac6-console/console.sh -u myuser -h myhost'  and put the password in a password in `~/Developer/idrac6-console/passwd' and 'chmod 600 ~/Developer/idrac6-console/passwd'.

Side note: if you don't supply a user or password it will default to the default login `root:calvin`.

Ps. Haarlem represents ;-)
